name: build_powershell

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: git checkout
      uses: actions/checkout@v2

    - name: setup .net
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: dotnet restore
      run: dotnet restore src/DurableFunctionsCLI.Core/DurableFunctionsCLI.Core.csproj

    - name: dotnet publish
      run: dotnet publish -o src/PowerShell/bin src/DurableFunctionsCLI.Core/DurableFunctionsCLI.Core.csproj

    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: PSDurableFunctions
        path: src/PowerShell

    - name: publish to psgallery
      shell: pwsh
      env:
        PSGALLERY_KEY: ${{ secrets.PSGALLERY_KEY }}
      run: |
        Install-Module -Name 'Az.Accounts' -MinimumVersion "2.2.1" -Force
        Rename-Item -Path "src/PowerShell" -NewName "PSDurableFunctions"
        Publish-Module -Repository 'PSGallery' -Path 'src/PSDurableFunctions' -NuGetApiKey $env:PSGALLERY_KEY
      if: startsWith(github.ref, 'refs/tags/v')